# Generated by Django 5.1 on 2024-10-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_client_id_alter_mailingattempt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='clients',
            field=models.ManyToManyField(related_name='mailings', to='mailings.client', verbose_name='Клиенты для рассылки'),
        ),
    ]
